### PR TITLE
BTA-8265 Adds Error Code 434

### PR DESCRIPTION
**Pull request by thirunjuguna**
Adds Error Code 434

Screenshot 2022-05-30 at 10 58 26

### CODE REVIEW

**Comment by evanson** [comment]
@thirunjuguna Small request, could you please add error code `415` in this PR, it wasn't added to the documentation when doing the OTP flow for GHS.

**Comment by thirunjuguna** [comment]
I think we already added that

**Comment by thirunjuguna** [comment]
https://github.com/transferzero/api-documentation/pull/107

**Comment by evanson** [comment]
@thirunjuguna  There's still one missing: `312`.

**Pull request merged**
