### PR TITLE
BTA-13586 Pre-transaction mandate validation

### PR DESCRIPTION
**Pull request by cesarecamurani**
BTA-13586 Pre-transaction mandate validation

Changes
---------

- Adds pre-transaction (validation) mandates handling documentation.

Screenshot 2024-05-16 at 15 27 53

Screenshot 2024-05-17 at 12 48 46
Screenshot 2024-05-16 at 17 21 20
Screenshot 2024-05-16 at 17 21 32
Screenshot 2024-05-16 at 17 21 47
Screenshot 2024-05-17 at 11 50 27
Screenshot 2024-05-21 at 08 50 13

### CODE REVIEW

**Review by evanson — COMMENTED** [review]
This should also documentation on the create transaction flow indicating that a ZAR transaction cannot be created without the mandate for some API users.

**Comment by cesarecamurani** [comment]
> This should also documentation on the create transaction flow indicating that a ZAR transaction cannot be created without the mandate for some API users.

Can you please provide a text for this @arnaugiro (where should we have it as well?)

**Comment by arnaugiro** [comment]
Hi @evanson , we discussed this with Cesare last week and I proposed to remove the initial note. However, I don't have strong opinions here, so we can add the informative note, something like:

`Getting a successful validate response before instructing a transaction might be a requirement depending on your configurations in AZA.`

The location should be at the end of the page, note/warning format.

Happy to receive other suggestions for the content

**Comment by evanson** [comment]
This can be added on this mandate flow page.

**Review by evanson — APPROVED** [review]

**Pull request merged**
